<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_floating_cart</name>
   <tag></tag>
   <elementGuidId>56a201a1-d0f9-446c-8c2d-26adf175601e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1xe5izx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div[2]/button[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81a28fbb-ef7d-4100-b848-f6f9cc02306b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xe5izx</value>
      <webElementGuid>f91a6fe6-4046-4234-b25c-f21cdf6bbf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total20.000untuk 2 produk</value>
      <webElementGuid>1c8cf275-5c80-461b-a6d3-c92cf68a97b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1ixgbcy&quot;]/div[@class=&quot;css-h5ftq&quot;]/div[@class=&quot;css-ffp25a&quot;]/button[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root  css-z5yaat&quot;]/div[@class=&quot;css-1xe5izx&quot;]</value>
      <webElementGuid>63104cb8-1ef1-43e2-8f9c-903b820ff370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[2]/button[2]/div</value>
      <webElementGuid>a5aed381-9699-4e76-88f6-40d449947c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/div</value>
      <webElementGuid>8d114a3c-a7b8-411d-936e-99fd84675c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Total20.000untuk 2 produk' or . = 'Total20.000untuk 2 produk')]</value>
      <webElementGuid>40e9c0de-df88-4505-9aa5-e80dc6e1e58a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
