<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_plus_product</name>
   <tag></tag>
   <elementGuidId>2c8d347f-d8d9-4ebc-8994-83d74c9f6763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/button[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95f05ad4-d9ae-4f15-b46b-57762d6e18c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-sjx0zd</value>
      <webElementGuid>d40cac0b-cf34-418e-8aab-b310b891476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>564073ed-7d24-4fa4-81a6-d9bb63277899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1ixgbcy&quot;]/div[@class=&quot;css-h5ftq&quot;]/div[@class=&quot;css-x4n4mc&quot;]/div[@class=&quot;css-x4n4mc&quot;]/div[@class=&quot;css-71m5jh&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;height-preserving-container css-ggera5&quot;]/div[@class=&quot;css-17pxf9o&quot;]/div[1]/div[@class=&quot;css-1773by3&quot;]/div[@class=&quot;css-127bjm&quot;]/div[@class=&quot;css-1vc4j1p&quot;]/div[@class=&quot;css-16kpiz3&quot;]/div[@class=&quot;css-167c46v&quot;]/div[@class=&quot;css-14l31q&quot;]/button[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root  css-z5yaat&quot;]/div[@class=&quot;MuiBox-root css-sjx0zd&quot;]</value>
      <webElementGuid>f8685dda-2684-4e89-be96-b1229952c8e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/button[2]/div</value>
      <webElementGuid>2dafbacf-2d15-40dd-b8cf-ac14feab4fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>a06fc44a-6740-4b9c-8f1a-7e437ccc4b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '+' or . = '+')]</value>
      <webElementGuid>07b113ed-53b5-4e3c-ac53-ba1af6803bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
