<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_location_cafe</name>
   <tag></tag>
   <elementGuidId>82b54e3b-b476-4c25-89cd-135de0741f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1ozv6b7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div/div/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e4a02fe-ad41-44bd-a189-7dcbe372b80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ozv6b7</value>
      <webElementGuid>cc619132-9c44-4b71-8ab1-3b45b83c869e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Very Good FranchiseeJl. Dr. Ir. H. Soekarno No.220, Semolowaru, Kec. Sukolilo, Kota SBY, Jawa Timur 6011742.14 KMopen</value>
      <webElementGuid>beee2eff-996e-420f-8169-cd68a582b8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1ixgbcy&quot;]/div[@class=&quot;css-r2g3i0&quot;]/div[@class=&quot;css-dcz2zc&quot;]/div[@class=&quot;css-15332r5&quot;]/div[@class=&quot;css-1w9c1xi&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiCard-root css-1okcig&quot;]/button[@class=&quot;MuiButtonBase-root MuiCardActionArea-root css-nbnz49&quot;]/div[@class=&quot;css-1ozv6b7&quot;]</value>
      <webElementGuid>ac45a650-ed47-4e73-9fe9-953179965531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div/div/div/button/div</value>
      <webElementGuid>319d594b-310c-4b84-828c-2d4922af5a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button/div</value>
      <webElementGuid>fcec9dd8-dc21-4f68-b0c3-dbc6520a0dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Very Good FranchiseeJl. Dr. Ir. H. Soekarno No.220, Semolowaru, Kec. Sukolilo, Kota SBY, Jawa Timur 6011742.14 KMopen' or . = 'Very Good FranchiseeJl. Dr. Ir. H. Soekarno No.220, Semolowaru, Kec. Sukolilo, Kota SBY, Jawa Timur 6011742.14 KMopen')]</value>
      <webElementGuid>cf79b386-371c-4e9e-b468-e38cbb1d019f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
