<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_product_ABIV</name>
   <tag></tag>
   <elementGuidId>3470e8e8-13a1-4fe4-8358-a29eac53744c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div/div/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-body1.css-anr7ky</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1ca1f556-88c8-4d4f-aa5e-cf5b8326b5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-anr7ky</value>
      <webElementGuid>3032d2fe-c2a8-46a1-b85f-345606799751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABIV</value>
      <webElementGuid>19ad58ec-6295-4e73-b544-929a083c1db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1ixgbcy&quot;]/div[@class=&quot;css-yvopwm&quot;]/div[@class=&quot;css-19ec3x4&quot;]/div[@class=&quot;css-1773by3&quot;]/div[@class=&quot;css-127bjm&quot;]/div[@class=&quot;css-56jipt&quot;]/div[@class=&quot;css-1kze96t&quot;]/div[@class=&quot;css-16xwqa5&quot;]/div[@class=&quot;css-1wff9y2&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-anr7ky&quot;]</value>
      <webElementGuid>5b0db742-8870-4ac4-adaf-d8b6e3a44c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div/div/div/div/div/div/div/p</value>
      <webElementGuid>47e75a07-f59b-4e3e-b219-3536d7343e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABIV']/parent::*</value>
      <webElementGuid>3c0ba9a0-0b39-47c5-ba9a-67218ff2565b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/p</value>
      <webElementGuid>bb4d9409-f75c-4cef-8d12-455ee2f15c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ABIV' or . = 'ABIV')]</value>
      <webElementGuid>1a560f4a-55df-4914-ac03-b4732e491eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
